name: IITM Email Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2002518@ds.study.iitm.ac.in
        run: echo "Hello from my email action!"
      - name: List files
        run: ls -l
